### ISSUE TITLE
The extension should ignore environment directories that are opened directly.

### ISSUE THREAD

**Issue by johnpaliotta** [vectorgrp/vector-vscode-vcast#172]
If your workspace root is a VectorCAST environment directory, the test pane will have an environment node with no name, and some commands like Re-Build Environment will fail because the directory cannot be deleted when it is open in the Workspace!

This edge case should not have been supported in the first place.

**Comment by aytey** [comment]
Can we give a notification when this happens to tell the user why they're not getting anything?

**Comment by johnpaliotta** [comment]
> Can we give a notification when this happens to tell the user why they're not getting anything?

yep, good idea
