### ISSUE TITLE
New test script might overwrite existing script

### ISSUE THREAD

**Issue by johnpaliotta** [vectorgrp/vector-vscode-vcast#20]
When a new test script is added same default name is always used.  For example: TEST.NAME:test-Manager::PlaceOrder
Because the test script has TEST.REPLACE vs TEST.NEW, if you create a test script and load it and then create a second script and load it the second test will over-write the first.

Workaround is to always select a unique name for the test.

**Comment by johnpaliotta** [comment]
Possible solutions:

- When creating a new test script don't generate a default name, this will cause vcast to choose a name on load
- When creating a new test ensure that a unique name is used as the default, append 1,2,3 etc.
- On load, scan the test script for the TEST.NAME line and ensure it is unique

**Comment by aytey** [comment]
Combining 2 + 3 seems like the closest to what VectorCAST does today, which I guess is a good thing
