### ISSUE TITLE
Invalid feature flag TEST.SCRIPT_FEATURE:RESET_ALL

### ISSUE THREAD

**Issue by joyyuansh** [vectorgrp/vector-vscode-vcast#5]
The line TEST.SCRIPT_FEATURE:RESET_ALL is added to test script file after loading a new test script into test script editor panel as below.
![image](https://github.com/vectorgrp/vector-vscode-vcast/assets/38112832/b957572c-df7a-4866-8ef4-922da4983fa0)

Follow these steps to reproduce the warning.
1. Right click a function and select VectorCAST | New test script
2. In the vcast-template.tst editor view, right click 'Load Test Script into Envrionment'
3. Wait VectorCAST Test Explorer reload the test script
4. Right click the environment node 'MANAGER' and select  VectorCAST | Edit Test Script

**Comment by johnpaliotta** [comment]
> The line TEST.SCRIPT_FEATURE:RESET_ALL is added to test script file after loading a new test script into test script editor panel as below. ![image](https://user-images.githubusercontent.com/38112832/257986183-b957572c-df7a-4866-8ef4-922da4983fa0.png)
> 
> Follow these steps to reproduce the warning.
> 
> 1. Right click a function and select VectorCAST | New test script
> 2. In the vcast-template.tst editor view, right click 'Load Test Script into Envrionment'
> 3. Wait VectorCAST Test Explorer reload the test script
> 4. Right click the environment node 'MANAGER' and select  VectorCAST | Edit Test Script

Could not repeat with vc23 sp2, let us know the version of vcast you are using.

**Comment by johnpaliotta** [comment]
Hover-over message in TEST.SCRIPT_FEATURE comments has a typo: 
"Invalid feature flag, * to see a all flags",

**Comment by johnpaliotta** [comment]
Add support for TEST.SCRIPT_FEATURE:RESET_ALL
