### ISSUE TITLE
The Unit Test Location option does not support relative paths with nesting

### ISSUE THREAD

**Issue by johnpaliotta** [vectorgrp/vector-vscode-vcast#76]
Values like "./tests/a/b/c" are not supported, but values like: "./tests" and "/home/user/tests/a/b/c" are supported.

When the value is set to "./tests/a/b/c" a build environment action will prompt to create the directory, but will do nothing and provide no warning message.

**Comment by aytey** [comment]
> and "/home/user/tests/a/b/c" are supported.

What happens if `/home/user/tests` doesn't exist when trying to use `/home/user/tests/a/b/c`?

**Comment by johnpaliotta** [comment]
> > and "/home/user/tests/a/b/c" are supported.
> 
> What happens if `/home/user/tests` doesn't exist when trying to use `/home/user/tests/a/b/c`?

We catch it when you set the option value
